[package]
name = "backup"
version = "0.2.20"
authors = []
edition = "2018"

[dependencies]
candid = "0.10.13"
ic-agent = "0.39.3"
tokio = { version = "1", features = ["full"] }

[workspace]
exclude = ["taggr/backup"]
