[package]
name = "upgrader"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
serde_bytes = "0.11.6"
canisters = { path = "../canisters" }


[features]
dev = []
