[package]
name = "bucket"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.10"
ic-cdk = "0.15.1"
ic-cdk-macros = "0.15.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_bytes = "0.11.15"

[features]
dev = []
