[package]
name = "bucket"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.3"
ic-cdk = "0.12.1"
ic-cdk-macros = "0.8.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_bytes = "0.11.12"

[features]
dev = []
