name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nodejs
      - uses: ./.github/actions/setup-build-deps

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend
        run: NODE_ENV=production npm run build --quiet

      - name: Build canister
        run: |
          ./build.sh bucket
          ./build.sh taggr

      - name: Rust lint
        run: cargo clippy --tests --benches -- -D clippy::all

      - name: Rust test
        run: cargo test

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Check Frontend formatting
        run: npm run format:check
