export const InviteInfo = () => {
    return (
        <article className="spaced">
            <div
                style={{
                    display: "flex",
                    justifyContent: "center",
                    marginTop: "2em",
                    marginBottom: "2em",
                }}
            >
                <svg
                    height="50px"
                    version="1.0"
                    viewBox="0 0 756 230"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <g transform="translate(0 230) scale(.1 -.1)">
                        <path d="m0 2070v-230h270 270v-920-920h180 180v920 920h270 270v230 230h-720-720v-230z" />
                        <path d="m1800 2070v-230h-90-90v-920-920h180 180v460 460h270 270v-460-460h180 180v920 920h-90-90v230 230h-450-450v-230zm720-460v-230h-270-270v230 230h270 270v-230z" />
                        <path d="m3240 2070v-230h-90-90v-690-690h90 90v-230-230h540 540v230 230h90 90v460 460h-270-270v-230-230h90 90v-230-230h-360-360v690 690h450 450v230 230h-540-540v-230z" />
                        <path d="m4860 2070v-230h-90-90v-690-690h90 90v-230-230h540 540v230 230h90 90v460 460h-270-270v-230-230h90 90v-230-230h-360-360v690 690h450 450v230 230h-540-540v-230z" />
                        <path d="m6300 1150v-1150h180 180v460 460h270 270v-460-460h180 180v460 460h-90-90v230 230h90 90v230 230h-90-90v230 230h-540-540v-1150zm900 460v-230h-270-270v230 230h270 270v-230z" />
                    </g>
                </svg>
            </div>
            <p className="x_large_text text_centered vertically_spaced">
                You've been invited — welcome!
            </p>
            <p className="info_item">
                <h2>💡 What is {window.backendCache.config.name}?</h2>
                <b>{window.backendCache.config.name}</b> is a decentralized
                social network owned by its users, not by any organization.
                Holders of the <a href="#/tokens">$TAGGR</a> token govern the
                platform through voting and receive a share of the revenue
                generated by {window.backendCache.config.name}.
            </p>
            <p className="info_item">
                <h2>🎭 Privacy first.</h2> To join{" "}
                <b>{window.backendCache.config.name}</b>, you only need a small
                amount of <code>BTC</code> or <code>ICP</code> cryptocurrency.
                No email, no phone, no KYC required. Your invite comes with
                starter credits already included.
            </p>
            <p className="info_item">
                <h2>🌟 No ads, no spam.</h2> Browsing is completely free, but
                posting and interactions require credits (you got some with this
                invite). Normal usage is cheap, and if your content is popular,
                you earn rewards and may never need to buy more credits. You can
                always top up with Bitcoin or ICP when needed.
            </p>
            <p className="info_item">
                <h2>🔐 Your data is 100% yours.</h2>
                No one can delete content published by you.{" "}
                {window.backendCache.config.name} is accessible through multiple
                domains controlled by different people. Each domain owner can
                configure filters to comply with local laws, but your data
                remains on the blockchain and is always accessible through other
                domains.
            </p>
            <p className="text_centered vertically_spaced">
                Ready? Pick an authentication method
                <br /> below to join.
            </p>
        </article>
    );
};
