name: "Setup Build Dependencies"
description: Setup Build Dependencies

runs:
  using: "composite"
  steps:
    - name: Get IC WASM version
      shell: bash
      run: echo "ic_wasm_version=$(cat .ic-wasm-version | xargs)" >> "$GITHUB_ENV"

    - name: Cache IC WASM
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/ic-wasm
        key: ic-wasm-cache-${{ env.ic_wasm_version }}

    - name: Install IC WASM
      shell: bash
      run: |
        if command -v ic-wasm
        then
          echo "IC WASM restored from cache"
        else
          echo "IC WASM not restored from cache, downloading:"
          curl -L https://github.com/dfinity/ic-wasm/releases/download/${{ env.ic_wasm_version }}/ic-wasm-linux64 -o /usr/local/bin/ic-wasm
          chmod +x /usr/local/bin/ic-wasm
        fi
        echo "IC WASM version"
        ic-wasm --version

    - name: Cache Candid Extractor
      uses: actions/cache@v3
      with:
        path: $HOME/.cargo/bin/candid-extractor
        key: candid-extractor-cache

    - name: Install Candid Extractor
      shell: bash
      run: |
        if command -v candid-extractor
        then
          echo "Candid Extractor restored from cache"
        else
          echo "Candid Extractor not restored from cache, installing:"
          cargo install candid-extractor@0.1.2
        fi
